In [1]:
import pandas as pd
import numpy as np
import pickle
pd.set_option('display.max_columns', 300)

## Step 1: Read in hold out data, scalers, and best model

In [34]:
holdout = pd.read_csv('kc_house_data_test_features.csv', index_col=0)

In [3]:
pickle_in = open('model.pickle', 'rb')
final_model = pickle.load(pickle_in)

## Step 2: Feature Engineering for holdout set

Remember we have to perform the same transformations on our holdout data (feature engineering, extreme values, and scaling) that we performed on the original data.

In [11]:
holdout['bedrooms_cat'] = holdout['bedrooms'].map(lambda x: 1 if (x == 0) | (x ==1) else\
                                                    2 if x ==2 else\
                                                    3 if x==3 else\
                                                    4 if x==4 else\
                                                    5 if x==5 else\
                                                    6 if x==6 else 7)
bdrm_dummies = pd.get_dummies(holdout['bedrooms_cat'], prefix='bdrm', drop_first=True)

holdout['bathrooms_cat'] = holdout['bathrooms'].map(lambda x: 1 if (x < 1) else\
                                                      2 if x ==1 else\
                                                      3 if (x > 1)&(x<=2) else\
                                                      4 if (x > 2)&(x<=3) else\
                                                      5 if (x > 3)&(x<=4) else\
                                                      6 if (x > 4)&(x<=5) else 7)
bthrm_dummies = pd.get_dummies(holdout['bathrooms_cat'], prefix='bthrm', drop_first=True)

holdout['floors_cat'] = holdout['floors'].map(lambda x: 1 if (x == 1) else\
                                                      2 if x ==1.5 else\
                                                      3 if x ==2 else\
                                                      4 if x ==2.5 else 5)
flrs_dummies = pd.get_dummies(holdout['floors_cat'], prefix='flr', drop_first=True)

view_dummies = pd.get_dummies(holdout['view'], prefix='view',drop_first=True)

condition_dummies = pd.get_dummies(holdout['condition'], prefix='condition', drop_first=True)

holdout['grade_cat'] = holdout['grade'].map(lambda x: 1 if (x >= 1)&(x<=5) else\
                                                      2 if (x >= 6)&(x<=7) else\
                                                      3 if (x >= 8)&(x<=9) else\
                                                      4 if (x == 10) else 5) 
grade_dummies = pd.get_dummies(holdout['grade_cat'], prefix='grade', drop_first=True)

holdout['basement_dummy'] = holdout['sqft_basement'].map(lambda x: 0 if (x == 0) else 1)

holdout['reno_dichotomous'] = holdout['yr_renovated'].map(lambda x: 0 if (x == 0) else 1)
holdout['year_sold'] = holdout['date'].map(lambda x: x[0:4])
holdout['year_sold'] = holdout['year_sold'].astype(int)
holdout['years_old'] = holdout['year_sold'] - holdout['yr_built']
holdout['years_oldXreno'] = holdout['years_old']*holdout['reno_dichotomous']

# holdout['log_price'] = np.log(holdout['price'])
holdout['log_sqft_living'] = np.log(holdout['sqft_living'])
holdout['log_sqft_lot'] = np.log(holdout['sqft_lot'])

holdout['squared_log_sqft_living'] = holdout['log_sqft_living']**2

# Concatenating all  variables 
holdout_full = pd.concat([holdout,bdrm_dummies,bthrm_dummies,flrs_dummies,view_dummies,condition_dummies,grade_dummies], axis=1)

predictors5 = ['log_sqft_living','squared_log_sqft_living', 'log_sqft_lot','waterfront','sqft_living15','basement_dummy',\
              'years_old', 'bdrm_2', 'bdrm_3', 'bdrm_4','bdrm_5', 'bdrm_6', 'bdrm_7',\
              'bthrm_2', 'bthrm_3','bthrm_4', 'bthrm_5', 'bthrm_6', 'bthrm_7',\
              'flr_2', 'flr_3','flr_4', 'flr_5','view_1', 'view_2',\
              'view_3', 'view_4','condition_2', 'condition_3', 'condition_4','condition_5',\
              'condition_5','grade_2','grade_3','grade_4','grade_5',\
              'reno_dichotomous', 'years_old','years_oldXreno']

transformed_holdout = holdout_full[predictors5]

In [12]:
transformed_holdout.head()

,log_sqft_living,squared_log_sqft_living,log_sqft_lot,waterfront,sqft_living15,basement_dummy,years_old,bdrm_2,bdrm_3,bdrm_4,bdrm_5,bdrm_6,bdrm_7,bthrm_2,bthrm_3,bthrm_4,bthrm_5,bthrm_6,bthrm_7,flr_2,flr_3,flr_4,flr_5,view_1,view_2,view_3,view_4,condition_2,condition_3,condition_4,condition_5,condition_5,grade_2,grade_3,grade_4,grade_5,reno_dichotomous,years_old,years_oldXreno
0,7.727535,59.714799,9.350102,0,2020,1,47,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,47,0
1,7.727535,59.714799,9.350102,0,2020,1,48,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,48,0
2,7.293018,53.188107,7.483807,0,1470,1,9,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,9,0
3,7.154615,51.188521,9.692767,0,1160,1,38,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,38,0
4,7.948032,63.171213,9.002824,0,2830,0,10,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,10,0

## Step 3: Predict the holdout set

In [21]:
final_answer = np.exp(final_model.predict(transformed_holdout))

## Step 4: Export your predictions

In [31]:
final_answer_df = pd.DataFrame(final_answer, columns=['holdout_pred'])

In [33]:
final_answer_df.to_csv('housing_preds_Eric_Roberts.csv')